server.port=8083
spring.application.name=download-service

# External service URLs
services.content-url=http://localhost:8082
services.verification-url=http://localhost:8084
services.logging-url=http://localhost:8085
