server.port=8080
spring.application.name=gateway-service

# Max file upload size forward rules
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB
spring.servlet.multipart.enabled=false

# Microservices URLs
services.auth-url=http://localhost:8081
services.content-url=http://localhost:8082
services.download-url=http://localhost:8083
services.logging-url=http://localhost:8085
