server.port=8086
spring.application.name=demo-client

# Gateway Service API Base
services.gateway-url=http://gateway-service:8080/api

# Local downloads directory for the client simulator
client.downloads-dir=./client_downloads

# Multipart file upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
